-- Versioned snapshots used by the TriClub server before workspace mutations.
-- Apply this migration before deploying the application version that writes backups.
create table if not exists public.workspace_backups (
  id bigint generated by default as identity primary key,
  workspace_id smallint not null,
  payload jsonb not null,
  source_revision text not null,
  created_at timestamptz not null default now(),
  reason text not null,
  row_count integer not null,
  column_count integer not null
);

create index if not exists idx_workspace_backups_created_at
  on public.workspace_backups (workspace_id, created_at desc, id desc);

alter table public.workspace_backups enable row level security;
revoke all on table public.workspace_backups from anon, authenticated;
revoke all on sequence public.workspace_backups_id_seq from anon, authenticated;
grant select, insert, delete on table public.workspace_backups to service_role;
grant usage, select on sequence public.workspace_backups_id_seq to service_role;
